dbconfig:
  file:
    location:  C:\opt\data\fang-order-api\config-cache
spring:
  main:
    banner-mode: "console" # banner輸出 off 关闭banner输出
  boot:
    admin:
      client:
        url: http://localhost:8080
#spring:
#  devtools:
#    add-properties: false #关闭devTools 功能
#  http:
#    log-request-details: false
application:
  title: "springboot文档查询"
  version: "2018-12-12"
management:
  endpoints:
    web:
      exposure:
        include: "*"


my:
  secret: "${random.value}"
  bignumber: "${random.long}"
  intnumber: "${random.int}"

#配置自定义starter参数
hello:
  msg: HengYu Boy
  show: true


